"""Add experience column to trainers

Revision ID: c63bc6b56f22
Revises: 16c4edf7da98
Create Date: 2025-08-17 23:30:14.814294

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c63bc6b56f22'
down_revision = '16c4edf7da98'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('payments')
    with op.batch_alter_table('clients', schema=None) as batch_op:
        batch_op.drop_column('amount_paid')
        batch_op.drop_column('payment_method')
        batch_op.drop_column('payment_date')

    with op.batch_alter_table('trainers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('experience', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('qualities', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('batch', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('photo', sa.String(length=100), nullable=True))
        batch_op.drop_column('specialization')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trainers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('specialization', sa.VARCHAR(length=100), nullable=True))
        batch_op.drop_column('photo')
        batch_op.drop_column('batch')
        batch_op.drop_column('qualities')
        batch_op.drop_column('experience')

    with op.batch_alter_table('clients', schema=None) as batch_op:
        batch_op.add_column(sa.Column('payment_date', sa.DATE(), nullable=True))
        batch_op.add_column(sa.Column('payment_method', sa.VARCHAR(length=50), nullable=True))
        batch_op.add_column(sa.Column('amount_paid', sa.FLOAT(), nullable=True))

    op.create_table('payments',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('client_id', sa.INTEGER(), nullable=False),
    sa.Column('amount', sa.FLOAT(), nullable=False),
    sa.Column('method', sa.VARCHAR(length=50), nullable=False),
    sa.Column('status', sa.VARCHAR(length=20), nullable=True),
    sa.Column('paid_on', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
