"""Add payment_method to clients

Revision ID: f45d28868ab1
Revises: 51cb7cc7a77a
Create Date: 2025-08-21 19:04:27.792775

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f45d28868ab1'
down_revision = '51cb7cc7a77a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('clients', schema=None) as batch_op:
        batch_op.add_column(sa.Column('payment_method', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('clients', schema=None) as batch_op:
        batch_op.drop_column('payment_method')

    # ### end Alembic commands ###
